// WASM TypeScript declarations placeholder
// Generated by wasm-pack, this is a stub for development

export interface ZenCoreInitInput {
  module_or_path?: WebAssembly.Module | string;
}

export interface ZenCore {
  init_db(): void;
  load_zl(bytes: Uint8Array): void;
  save_zl(): Uint8Array;
  query(sql: string, params_json: string): string;
  execute(sql: string, params_json: string): number;
  render_markdown(input: string): string;
  get_epub_meta(bytes: Uint8Array): string;
  add_attachment(row_id: number, col: string, filename: string, mime: string, data: Uint8Array): number;
  get_attachment(id: number): Uint8Array;
  list_tables(): string;
  get_schema(table: string): string;
  rename_column(table: string, old_name: string, new_name: string): void;
  add_column(table: string, col_name: string, col_type: string): void;
}

export default function init(input?: string | ZenCoreInitInput): Promise<ZenCore>;
